name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'angular-ani/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./angular-ani/ani/
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build --prod
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        working-directory: ${{env.working-directory}}
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANIME_POC }}'
          channelId: live
          projectId: anime-poc
        env:
          PROJECT_PATH: ${{env.working-directory}}
